import React from 'react';

// App.tsx와 완벽하게 일치하는 엄격한 타입
type ViewMode = 'intro' | 'main' | 'guess' | 'build' | 'terms' | 'privacy' | 'about' | 'contact' | 'disclosure';

interface PageProps {
  setViewMode: (mode: ViewMode) => void;
}

export default function TermsOfService({ setViewMode }: PageProps) {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center p-6 md:p-12 animate-fade-in w-full overflow-y-auto">
      <div className="w-full max-w-4xl text-left bg-white p-8 md:p-12 rounded-3xl shadow-sm border border-gray-100 mt-10">
        
        {/* 뒤로 가기 버튼 */}
        <button 
          onClick={() => setViewMode('intro')} 
          className="mb-8 text-gray-400 hover:text-teal-600 font-bold text-sm transition-colors flex items-center gap-1"
        >
          ← Back to Home
        </button>

        {/* 문서 헤더 */}
        <div className="border-b border-gray-100 pb-8 mb-8">
          <h1 className="text-3xl md:text-4xl font-black mb-4 text-gray-900 tracking-tight">Holiday Hub Terms of Service</h1>
          <div className="text-sm text-gray-500 flex flex-col gap-1 font-medium">
            <p>Effective Date: [To be inserted]</p>
            <p>Last Updated: [To be inserted]</p>
          </div>
        </div>

        {/* 헌법(본문) 시작 */}
        <div className="space-y-8 text-gray-600 text-sm md:text-base leading-relaxed">
          
          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">1. Welcome to Holiday Hub</h2>
            <p className="mb-2">Welcome to Holiday Hub.</p>
            <p className="mb-2">Holiday Hub is an AI-powered travel planning platform designed to help people transform travel ideas into real journeys. By combining intelligent itinerary generation, travel planning tools, and access to trusted third-party booking services, we aim to make travel planning simpler, more confident, and more enjoyable.</p>
            <p className="mb-2">These Terms of Service ("Terms") form a legally binding agreement between you ("User", "Member", or "you") and Holiday Hub ("Holiday Hub", "Company", "we", "our", or "us").</p>
            <p className="mb-2">By accessing, browsing, creating an account, signing in, or using any part of Holiday Hub, you acknowledge that you have read, understood, and agree to these Terms.</p>
            <p className="font-bold text-gray-800">If you do not agree, please do not use Holiday Hub.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">2. Definitions</h2>
            <p className="mb-3">For the purposes of these Terms:</p>
            <ul className="list-disc pl-5 space-y-2 text-gray-600">
              <li><strong>Holiday Hub</strong> means the travel planning platform operated by the Company.</li>
              <li><strong>User</strong> means any individual accessing or using the Service.</li>
              <li><strong>Member</strong> means a User who creates an account or signs in using a supported authentication provider.</li>
              <li><strong>AI Itinerary</strong> means any itinerary, recommendation, destination suggestion, travel schedule, budget estimate, checklist, or other content generated by artificial intelligence.</li>
              <li><strong>Build My Travel</strong> refers to Holiday Hub's travel planning tools that assist users who already have a destination in mind.</li>
              <li><strong>Guess My Travel</strong> refers to Holiday Hub's guided recommendation experience for users who are still deciding where to travel.</li>
              <li><strong>Third-Party Services</strong> means any external websites, booking platforms, payment providers, travel agencies, airlines, accommodation providers, activity providers, or partners linked through Holiday Hub.</li>
              <li><strong>Affiliate Partner</strong> means any company that provides Holiday Hub with referral commissions when users complete qualifying transactions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">3. Our Service</h2>
            <p className="mb-3">Holiday Hub provides tools to assist users in:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>discovering travel destinations,</li>
              <li>generating AI-powered travel itineraries,</li>
              <li>estimating travel budgets,</li>
              <li>organising travel plans,</li>
              <li>accessing third-party travel booking services.</li>
            </ul>
            <p className="mb-3 font-semibold text-gray-700">Holiday Hub is not:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>a travel agency;</li>
              <li>an airline;</li>
              <li>a hotel operator;</li>
              <li>a tour operator;</li>
              <li>a payment processor;</li>
              <li>a visa consultant;</li>
              <li>a provider of travel insurance.</li>
            </ul>
            <p>Any booking, purchase, reservation, payment, or travel contract is entered directly between you and the relevant Third-Party Service. Holiday Hub is not a party to those agreements.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">4. Eligibility</h2>
            <p className="mb-2">You must comply with the laws applicable in your jurisdiction to use Holiday Hub.</p>
            <p className="mb-2">If you create an account, you agree that the information you provide is accurate and kept reasonably up to date.</p>
            <p>You are responsible for maintaining the security of your account.</p>
          </section>

          <section className="bg-amber-50/50 p-6 rounded-2xl border border-amber-100">
            <h2 className="text-xl font-black text-amber-900 mb-3">5. AI-Generated Content</h2>
            <p className="mb-2 text-amber-800">Holiday Hub uses artificial intelligence to generate travel recommendations and planning assistance. AI-generated content is intended solely to assist your planning and decision-making.</p>
            <p className="mb-4 text-amber-800">Although we strive to improve accuracy, AI-generated content may contain inaccuracies, omissions, outdated information, or recommendations that may not suit your personal circumstances. Before making any travel decision, you should independently verify important information, including but not limited to:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4 text-amber-900 font-medium">
              <li>flight schedules;</li>
              <li>accommodation availability;</li>
              <li>pricing;</li>
              <li>visa requirements;</li>
              <li>passport validity;</li>
              <li>government travel advisories;</li>
              <li>health requirements;</li>
              <li>local laws;</li>
              <li>weather conditions.</li>
            </ul>
            <p className="font-bold text-amber-900">Holiday Hub does not guarantee that AI-generated information is complete, accurate, current, or suitable for your specific travel plans.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">6. Third-Party Booking Services</h2>
            <p className="mb-2">Holiday Hub may provide links, widgets, integrations, or recommendations to Third-Party Services.</p>
            <p className="mb-4">When you choose to leave Holiday Hub and use a Third-Party Service, your relationship is governed solely by that provider's terms and policies. Holiday Hub does not:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>process payments;</li>
              <li>issue tickets;</li>
              <li>confirm reservations;</li>
              <li>manage cancellations;</li>
              <li>process refunds;</li>
              <li>control pricing or availability.</li>
            </ul>
            <p className="font-semibold">Any dispute relating to a booking must be resolved directly with the relevant Third-Party Service.</p>
          </section>

          <section className="bg-teal-50/50 p-6 rounded-2xl border border-teal-100">
            <h2 className="text-xl font-black text-teal-900 mb-3">7. Affiliate Disclosure</h2>
            <p className="mb-2 text-teal-800">Some links presented through Holiday Hub may be affiliate links. If you make a qualifying purchase through one of these links, Holiday Hub may receive a commission at no additional cost to you.</p>
            <p className="mb-2 text-teal-800">Affiliate relationships do not guarantee that a provider will appear in our recommendations, nor do they guarantee preferential ranking solely because a commission may be available.</p>
            <p className="font-bold text-teal-900">Our objective is to assist users in making informed travel decisions.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">8. User Responsibilities</h2>
            <p className="mb-3">You agree to use Holiday Hub responsibly. You remain solely responsible for:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>verifying all travel information;</li>
              <li>complying with immigration requirements;</li>
              <li>obtaining visas where required;</li>
              <li>maintaining valid travel documents;</li>
              <li>purchasing travel insurance where appropriate;</li>
              <li>complying with applicable laws during your travels.</li>
            </ul>
            <p className="font-semibold">Holiday Hub does not make travel decisions on your behalf. Final decisions always remain yours.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">9. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>misuse the Service;</li>
              <li>interfere with our systems;</li>
              <li>attempt unauthorized access;</li>
              <li>reverse engineer the platform;</li>
              <li>use automated scraping tools without permission;</li>
              <li>upload malicious software;</li>
              <li>violate intellectual property rights;</li>
              <li>use Holiday Hub for unlawful purposes.</li>
            </ul>
            <p className="font-semibold">We reserve the right to suspend or terminate accounts that violate these Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">10. Intellectual Property</h2>
            <p className="mb-2">All software, branding, logos, designs, interfaces, AI workflows, text, graphics, and original content provided by Holiday Hub remain the intellectual property of Holiday Hub or its licensors unless otherwise stated.</p>
            <p>These Terms do not transfer ownership of any intellectual property to users.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">11. Availability of Service</h2>
            <p className="mb-2">We continually improve Holiday Hub. Features may be modified, added, suspended, or removed without prior notice.</p>
            <p className="mb-2">We do not guarantee uninterrupted availability of the Service.</p>
            <p>Temporary interruptions may occur due to maintenance, technical issues, security updates, or events beyond our reasonable control.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">12. Limitation of Liability</h2>
            <p className="mb-3 font-semibold">To the maximum extent permitted by applicable law, Holiday Hub shall not be liable for any indirect, incidental, consequential, special, or punitive damages arising from your use of the Service. This includes, but is not limited to:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>travel disruptions;</li>
              <li>booking failures;</li>
              <li>pricing changes;</li>
              <li>missed flights;</li>
              <li>accommodation issues;</li>
              <li>reliance on AI-generated recommendations;</li>
              <li>actions or omissions of Third-Party Services.</li>
            </ul>
            <p>Nothing in these Terms excludes any rights that cannot legally be excluded under applicable consumer protection laws.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">13. Changes to These Terms</h2>
            <p className="mb-2">We may update these Terms from time to time. Where required by law, we will notify users of material changes.</p>
            <p>Continued use of Holiday Hub after updated Terms become effective constitutes acceptance of those revised Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">14. Governing Law</h2>
            <p>These Terms shall be governed by the laws applicable to the jurisdiction in which Holiday Hub is legally established, unless mandatory consumer protection laws require otherwise.</p>
          </section>

          <section>
            <h2 className="text-xl font-black text-gray-800 mb-3">15. Contact</h2>
            <p className="mb-2">If you have questions regarding these Terms, please contact us using the contact details provided on the Holiday Hub website.</p>
            <p className="font-bold text-teal-700 mt-6">Thank you for choosing Holiday Hub. We hope to help turn your travel ideas into real journeys.</p>
          </section>

        </div>
      </div>
    </div>
  );
}